# Generated by Django 4.1.1 on 2023-01-06 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asanas',
            old_name='asana',
            new_name='asana1',
        ),
        migrations.AddField(
            model_name='asanas',
            name='asana2',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asanas',
            name='asana3',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asanas',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='asanas',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='asanas',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
