# Generated by Django 4.1.1 on 2023-01-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_asanas_img1_alter_asanas_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('find', models.CharField(max_length=50)),
            ],
        ),
    ]
