# Generated by Django 4.1.1 on 2023-01-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_det'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asanas',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='asanas',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='asanas',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
