# Generated by Django 4.1.1 on 2023-01-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_asanas_img1_alter_asanas_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_det',
            name='age',
            field=models.IntegerField(max_length=100),
        ),
    ]
